sonar.projectKey=arepabuelas-backend
sonar.projectName=Arepabuelas Backend
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.token=sqa_57a4315c1cf59d5f2a50a3a7204fd6b773f62290

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*

sonar.javascript.lcov.reportPaths=coverage/lcov.info


sonar.language=js
sonar.host.url=http://localhost:9000
sonar.login=admin